#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/*.eMesh > /dev/null 2>&1
# rm -f constant/triSurface/*.stl > /dev/null 2>&1
rm -f constant/polyMesh/boundary

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -f 0/cellToRegion

for region in gas sphere box_xmin box_xmax
do
    rm -rf 0/${region}/cellToRegion constant/${region}/polyMesh
done

#------------------------------------------------------------------------------
