#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#  Definition de la geometrie - DOIT être exécuté EN PREMIER
#  pour modifier les fichiers INI avant de les copier
cd Geom_Salome_STLFiles
./Allrun_Geo_Salome_STLFiles
cd ..

#  Ajustement des fichiers (APRÈS exécution de Salome)
cp -r Geom_Salome_STLFiles/Files_INI/controlDict_INI system/controlDict
cp -r Geom_Salome_STLFiles/Files_INI/blockMeshDict_INI system/blockMeshDict
cp -r Geom_Salome_STLFiles/Files_INI/snappyHexMeshDict_INI system/snappyHexMeshDict

# Note: Les fichiers de post-traitement (Probes, Graphs, Scripts) sont déjà
# copiés et configurés par __MAIN__Geom_salome.py dans system/ et case_treatment/

#./Allmesh.Nolayers  #
./Allmesh.layers      

runApplication decomposePar -allRegions -copyZero -constant

runParallel $(getApplication)

runApplication reconstructParMesh -allRegions -constant
runApplication reconstructPar -allRegions

# Nettoyage des processeurs
rm -r processor*

echo "----------------------------------------------------------------"
echo "Running Post-Processing Scripts..."
echo "----------------------------------------------------------------"

echo "1. Plot_Residus.py (Residuals)"
python3 case_treatment/Plot_Residus.py

echo "2. Plot_Probes.py (Temperature Probes)"
python3 case_treatment/Plot_Probes.py

echo "3. Plot_XProfile.py (Temperature Profile along X)"
python3 case_treatment/Plot_XProfile.py

echo "4. Plot_HeatFlux.py (Heat Flux & Energy Balance)"
python3 case_treatment/Plot_HeatFlux.py

echo
echo "Creating files for ParaView..."
echo
paraFoam -touchAll

echo "----------------------------------------------------------------"
echo "Done."
echo "----------------------------------------------------------------"
