#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#  Definition de la geometrie - DOIT être exécuté EN PREMIER
#  pour modifier les fichiers INI avant de les copier
cd Geom_Salome_STLFiles
./Allrun_Geo_Salome_STLFiles
cd ..

#  Ajustement des fichiers (APRÈS exécution de Salome)
cp -r Geom_Salome_STLFiles/Files_INI/controlDict_INI system/controlDict
cp -r Geom_Salome_STLFiles/Files_INI/blockMeshDict_INI system/blockMeshDict
cp -r Geom_Salome_STLFiles/Files_INI/snappyHexMeshDict_INI system/snappyHexMeshDict

cp -r Geom_Salome_STLFiles/Files_INI/T_Average_inlet system/T_Average_inlet
cp -r Geom_Salome_STLFiles/Files_INI/T_Average_outlet system/T_Average_outlet

cp Geom_Salome_STLFiles/Graph_et_Probes_INI/* system/

cp Geom_Salome_STLFiles/Scripts_Plots_INI/* case_treatment/

#./Allmesh.Nolayers  #
./Allmesh.layers      

runApplication decomposePar -allRegions -copyZero -constant

runParallel $(getApplication)

runApplication reconstructParMesh -allRegions -constant
runApplication reconstructPar -allRegions

chtMultiRegionFoam -postProcess -func ZGraph_Centre_Water >log.ZGraph_Centre_Water
chtMultiRegionFoam -postProcess -func ZGraph_Centre_Solid >log.ZGraph_Centre_Solid

chtMultiRegionFoam -postProcess -func ZGraph_CentreTubeSortie_Water >log.ZGraph_CentreTubeSortie_Water
chtMultiRegionFoam -postProcess -func ZGraph_CentreTubeSortie_Solid >log.ZGraph_CentreTubeSortie_Solid

chtMultiRegionFoam -postProcess -func ZGraph_CoteSortie_Solid >log.ZGraph_CoteSortie_Solid
chtMultiRegionFoam -postProcess -func ZGraph_CoteEntree_Solid >log.ZGraph_CoteEntree_Solid

chtMultiRegionFoam -postProcess -func Surface_outlet_VTK >log.Surface_outlet_VTK

rm -r processor*

echo "Plot_Residus.py...."
python3 case_treatment/Plot_Residus.py

echo "Plot_Graph_CSV.py...."
python3 case_treatment/Plot_Graph_CSV.py

echo "Plot_Probes.py...."
python3 case_treatment/Plot_Probes.py

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll
#paraview
#------------------------------------------------------------------------------
